name: ritmistas_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  jwt_decoder: ^2.0.1
  
  # --- VERSÕES TRAVADAS PARA DOCKER (SEM O ^) ---
  mobile_scanner: 5.2.3
  url_launcher: 6.2.6
  image_picker: 1.1.2
  
  # Firebase & Google (versões atualizadas para Dart >=3.6)
  firebase_core: ^3.15.0
  firebase_storage: ^12.2.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.3.0
  # -----------------------------------------------
  
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  clipboard: ^2.0.1
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  # SEM ASSETS (Usamos URL)