name: ritmistas_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  jwt_decoder: ^2.0.1
  
  # --- VERSÕES TRAVADAS (SEM O ^) ---
  # Estas versões funcionam GARANTIDAMENTE no Docker do Render
  mobile_scanner: 5.2.3
  url_launcher: 6.3.0
  image_picker: 1.1.2
  firebase_core: 3.4.0
  firebase_storage: 12.2.0
  # ----------------------------------
  
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  clipboard: ^2.0.1
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # SEM ASSETS LOCAIS (Usamos links da web para evitar erros de Linux)