name: ritmistas_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Relaxei a exigência mínima para garantir compatibilidade

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  jwt_decoder: ^2.0.1
  
  # VERSÕES BLINDADAS (Compatíveis com Flutter 3.22 / Dart 3.4):
  mobile_scanner: 5.2.3     # Versão extremamente estável
  url_launcher: 6.2.6       # Versão garantida para este SDK
  qr_flutter: ^4.1.0
  intl: ^0.19.0             # Versão estável padrão
  clipboard: ^2.0.1
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Downgrade para evitar conflito de SDK 3.5+
  flutter_lints: ^3.0.0    

flutter:
  uses-material-design: true

  assets:
    - assets/images/logoB10.png