name: ritmistas_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  jwt_decoder: ^2.0.1
  
  # USANDO VERSÃO 5.2.3 (Super Estável) - SEM O '^'
  
  # USANDO VERSÃO 6.2.6 (Compatível com Docker) - SEM O '^'
  url_launcher: 6.2.6
  
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  clipboard: ^2.0.1
  curved_navigation_bar: ^1.0.6
  mobile_scanner: ^6.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  # SEM ASSETS AQUI (Usaremos links da web)

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/iconb10.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000" # Fundo preto
  adaptive_icon_foreground: "assets/images/iconb10.png"