name: ritmistas_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  jwt_decoder: ^2.0.1
  mobile_scanner: ^6.0.11  # Versão compatível com o Render
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  clipboard: ^2.0.2
  curved_navigation_bar: ^1.0.6 # Nova barra de navegação
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0    # Versão compatível com o Render

flutter:
  uses-material-design: true

  # Configuração da Imagem
  assets:
    - assets/images/logob10.png